### ISSUE TITLE
Preview mode not working

### ISSUE THREAD

**Issue by jamesvclements** [sanity-io/sanity-template-nextjs-app-router-personal-website#31]
Any insights on why preview mode wouldn't be showing draft content?
I just did a clean clone, npm install, and linked it to a project with the ID, dataset set to production, and read token.

**Comment by stipsan** [comment]
We just updated to `draftMode` APIs and `next-sanity` `v5`, end to end tests are working so I'm closing this issue.
Feel free to re-open should you still be affected 🙌
