### ISSUE TITLE
`previewData` from `next/headers` removed in NextJS 13.4, causing build error

### ISSUE THREAD

**Issue by jasopolis** [sanity-io/sanity-template-nextjs-app-router-personal-website#32]
In NextJS 13.4 (also where the App router is declared as production-ready), the ["Preview Mode" feature](https://nextjs.org/docs/pages/building-your-application/configuring/preview-mode) is superseded/deprecated, and intended to be replaced with [Draft Mode](https://nextjs.org/docs/pages/building-your-application/configuring/draft-mode).

As a result, the `previewData` function used in `lib/sanity.server.ts` is removed entirely, which breaks this template when upgrading to Next 13.4. This also seems to be the reason #28 [is failing CI](https://github.com/sanity-io/sanity-template-nextjs-appdir-personal-website/actions/runs/5023302657/jobs/9007743074?pr=28).

Here's a related issue in `next-sanity` talking about the issue, with a proposed solution by migrating to the Draft Mode: https://github.com/sanity-io/next-sanity/issues/400

If you're accepting PRs, I'd be happy to try a fix for this! Thanks :)

**Comment by JamesSingleton** [comment]
@jasopolis I would just open a PR 🎉 I _think_ `previewData` can just be replaced by `draftMode` and take the `isEnabled` off of it and use it that way. https://nextjs.org/docs/app/api-reference/functions/draft-mode
