### ISSUE TITLE
Revalidation is missing in the example

### ISSUE THREAD

**Issue by AdisonCavani** [sanity-io/sanity-template-nextjs-app-router-personal-website#39]
In the README.md:

> Webhook-triggered Incremental Static Revalidation; no need to wait for a rebuild to publish new content

In the code I cannot see any code related to revalidation

**Comment by JamesSingleton** [comment]
@AdisonCavani That is true, you can look at https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/blob/main/pages/api/revalidate.ts for an example of how to do it in the `pages` directory. Since this template is still using the pages directory for the APIs, you could slot this in.
