### ISSUE TITLE
No revalidation of data in production environment.

### ISSUE THREAD

**Issue by smoxx** [sanity-io/sanity-template-nextjs-app-router-personal-website#52]
I setup the project and deployed it to vercel, exactly as described in your guide. Now, creating data and previewing isn't a problem at all, that works great. The problem is, that after publishing data and exiting the preview mode, no data is being displayed. The site is statically generated and not invalidated when content changes are published. 
Could you please provide a fix, because it is a rather important feature to display content in the production environment.

**Comment by stipsan** [comment]
We will be adding this soon, we've been busy upgrading `@sanity/client` to support new features like `revalidateTag` that is a great fit for this template :D 🔨

**Comment by marcinwenger** [comment]
Is there any workaround for this in the meantime? Thanks

**Comment by stipsan** [comment]
Revalidation using the new `revalidateTag` API has been added: https://github.com/sanity-io/sanity-template-nextjs-app-router-personal-website/blob/main/app/api/revalidate/route.ts
