### ISSUE TITLE
Sanity integration with NextJS doesn't allow log in

### ISSUE THREAD

**Issue by a160v** [sanity-io/sanity-template-nextjs-app-router-personal-website#59]
Hi there, I am following the guide to deploy a NextJS project with Sanity on Vercel.
When I try to activate the Sanity integration, the login buttons don't work and I cannot go any further. There are three login options but none of them seems to be working, please [check the screen recording.](https://drive.google.com/file/d/1YTC8Jasae7fDWRCoT5zYTdRcGTNDgswQ/view?usp=sharing) 
This step blocks the whole process, so I would consider the issue critical. 
I could replicate the error on both Arc and Google Chrome, with ublocker deactivated.

**Comment by stipsan** [comment]
Hi, this should be resolved now!

**Comment by a160v** [comment]
All solved, thank you @stipsan
